
<body>

 <div class="container" >
  <!-- meni -->
<?php 
  $select = $this->select;
  $select->prepare();
  $select->setAttribute('action', $this->url('application/index', array('controller'=>'index', 'action' => 'sort')));
  $select->setAttribute('method', 'post');
  $select->setAttribute('id','moja');
  $select->setAttribute('role','form');
  $select->setAttribute('class','form-inline');
  echo $this->form()->openTag($select);
 ?>

     <nav class="navbar navbar-inverse">
       <div class="container-fluid">
         <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>                        
            </button>
            <div class="nav-logo">
              <img class="img-responsive" src="<?php echo $this->basePath('img/en-logo.png') ?>"/>
            </div>
         </div>
         <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <li ><a href="<?php echo $this->url('application/default');?>" >Početna</a></li>
              <?php if ($korisnik == null) :?>
              <li><a href="<?php echo $this->url('application/register',array('action'=>'index'));?>">Registracija</a></li>
              <?php endif?>
              <li><a href="<?php echo $this->url('application/index',array('action'=>'gallery'));?>">Galerija</a></li>
              <li><a href="<?php echo $this->url('application/index',array('action'=>'contact'));?>">Kontakt</a></li>
              <li ><a><?php echo $this->formElement($select->get('kategorije')->setAttributes(array('class'=>'select_menu','onChange'=>'document.forms["moja"].submit()'))->setOptions(array('empty_option'=>'Kategorije','value_options'=>$kat)));?></a></li>
              <?php if ($korisnik != null) :?>
              <li ><a href="<?php echo $this->url('application/index', array('action'=>'logout'));?>">Logout</a></li>
              <li ><a href="<?php echo $this->url('application/korisnik', array('action'=>'index'));?>" ><?php echo $korisnik?></a></li>
              <?php endif?>        
           </ul>
        </div>
      </div>
     </nav>

 <?php echo $this->form()->closeTag()?>
 <!-- kraj menija -->
    
  <div class="row">
    <div class="col-md-2"></div><!-- prva kolona prazna -->
    <div class="col-md-7"><!-- druga kolona forma-->
      <div class="contact">
        <p>
           Event Nis zadržava pravo izbora komentara koji će biti objavljeni, kao i pravo skraćivanja komentara.
           Komentare koji sadrže govor mržnje*, psovke i uvrede, kao i komentare koji se ne odnose na vest koju komentarišete, ne objavljujemo.
           Komentare kojima nam skrećete pažnju na slovne greške, tehničke i druge propuste ne objavljujemo, kao i komentare koji se odnose na uređivačku politiku, ali će biti prosleđeni urednicima i na tome se zahvaljujemo.
           Molimo vas da obratite pažnju na pravopisnu i gramatičku ispravnost komentara koje šaljete, prednost će imati komentari koji su napisani bez pravopisnih i gramatičkih grešaka.
           Ukoliko želite da opširno polemišete, registrujte se na Forumu.
           Tekst komentara ograničen je na 1500 karaktera.
       </p>
       <p>
           * Zakon o javnom informisanju – član 38: Zabranjeno je objavljivanje ideja, informacija i mišljenja kojima se podstiče diskriminacija, mržnja ili nasilje protiv lica ili grupe lica zbog njihovog pripadanja ili nepripadanja nekoj rasi, veri, naciji, etničkoj grupi, polu ili zbog njihove seksualne opredeljenosti, bez obzira na to da li je objavljivanjem učinjeno krivično delo.
           Mišljenja izneta u komentarima su privatno mišljenje autora komentara i ne predstavljaju stavove Event Nis-a. Ipak po postojećem Zakonu o javnom informisanju Event Nis odgovara za sve sadržaje koji se nalaze na njegovim veb adresama pa će se tako i odnositi prema komentarima čitalaca.
       </p> 
	
		<?php
           $form = $this->form;
           $form->prepare();
           $form->setAttribute('action', $this->url(NULL,array('controller'=>'post', 'action' => 'createkom', 'id'=>$id)));
           $form->setAttribute('method', 'post');
           $form->setAttribute('role','form');
           $form->setAttribute('class','form-horizontal');
           echo $this->form()->openTag($form);
         ?>
         <div class="contact-form">
         <h3>Ostavi komentar</h3>	
           <div class="form-group">
             <label class="control-label col-sm-2"><?php echo $this->formLabel($form->get('komentar')); ?></label>
             <div class="col-sm-8">
                <?php 
                    echo $this->formElement($form->get('komentar')->setAttributes(array('class'=>'form-control input-sm','rows'=>'5')));
                    echo $this->formElementErrors($form->get('komentar')->setAttributes(array('class'=>'form-control input-sm')));
                 ?>
             </div>
           </div>
           <div class="form-group">        
             <div class="col-sm-offset-2 col-sm-10">
               <?php echo $this->formElement($form->get('submit')->setAttributes(array('class'=>'btn btn-default')));
                     echo $this->formElementErrors($form->get('submit'));?>
             </div>
           </div>
           <span><?php if($this->mssg) echo 'Poruka je uspešno poslata'?></span> 
           </div>
           <?php echo $this->form()->closeTag()?>  
       </div>
    </div>   
    <div class="col-md-3"><!-- treca kolona login -->       
       <div class="baner">
          <img class="img-responsive" src="<?php echo $this->basePath('img/events.jpg') ?>"/>
       </div>
	   <div class="facebook-groups">
	     <h3>U gradu...</h3>	  
	     <ul class="list-group">
           <li><a href="<?php echo $this->url('application/facebook',array('action'=>'index','id'=>'149480451883510'));?>">Bioskop Vilin Grad</a></li>
           <li><a href="<?php echo $this->url('application/facebook',array('action'=>'video','id'=>'145925982238957'));?>">Bioskop Vilin Grad - Trejleri</a></li>
           <li><a href="<?php echo $this->url('application/facebook',array('action'=>'index','id'=>'309874462392268'));?>">Bioskop Kupina film</a></li>
           <li><a href="<?php echo $this->url('application/facebook',array('action'=>'index','id'=>'203592859777305'));?>">Narodno pozorište Niš</a></li>
        </ul>
	  </div>
   
    </div>
  
  </div>
</div>

</body>
</html>
