
<body>

 <div class="container" >
  <!-- meni -->
  <?php 
  $select=$this->select;
  $select->prepare();
  $select->setAttribute('action', $this->url('application/index', array('controller'=>'index', 'action' => 'sort')));
  $select->setAttribute('method', 'post');
  $select->setAttribute('id','moja');
  $select->setAttribute('role','form');
  $select->setAttribute('class','form-inline');
  echo $this->form()->openTag($select);
 ?>
 

     <nav class="navbar navbar-inverse">
       <div class="container-fluid">
         <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>                        
            </button>
            <div class="nav-logo">
              <img class="img-responsive" src="<?php echo $this->basePath('img/en-logo.png') ?>"/>
            </div>
         </div>
         <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <li ><a href="<?php echo $this->url('application/default');?>" >Početna</a></li>
              <?php if ($this->korisnik == null) :?>
              <li><a href="<?php echo $this->url('application/register',array('action'=>'index'));?>">Registracija</a></li>
              <?php endif?>
              <li><a href="<?php echo $this->url('application/index',array('action'=>'gallery'));?>">Galerija</a></li>
              <li><a href="<?php echo $this->url('application/index',array('action'=>'contact'));?>">Kontakt</a></li>
              <li><a><?php echo $this->formElement($select->get('kategorije')->setAttributes(array('class'=>'select_menu','onChange'=>'document.forms["moja"].submit()'))->setOptions(array('label_attributes' => array('class' => 'options'),'empty_option'=>'Kategorije','value_options'=>$this->kat)));?></a></li>
              <?php if ($this->korisnik != null) :?>
              <li ><a href="<?php echo $this->url('application/index', array('action'=>'logout'));?>">Logout</a></li>
              <li ><a href="<?php echo $this->url('application/korisnik', array('action'=>'index'));?>"><?php echo $this->korisnik?></a></li>
              <?php endif?>        
           </ul>
        </div>
      </div>
     </nav>

  <?php echo $this->form()->closeTag()?>
  <!-- kraj menija -->
  
  <div class="row">
    <div class="col-md-2"></div><!-- prva kolona prazna -->
    <div class="col-md-7"><!-- druga kolona postovi-->
       <?php foreach ($this->feeds as $post):?>
	   <div class="post-box">  
	      <div class="post-box-header">
		    <p class="date">
		        <?php echo $format = $post['updated_time']->format('d.m.Y'); ?>
			</p>
			<p class="category"><?php echo $this->naslov ?></p>
		  </div>
		  <br />
          <video  class="post-box-video" controls>
              <source src="<?php echo $this->url('application/facebook', array('action'=>'prikaz', 'id' => $post['id'], 'direction'=>'video'));?>" ></source>
          </video>
		  <br />
          <span>
             <?php 
                if(isset($post['description']))
                {
                   // The Regular Expression filter
                   $reg_exUrl = "/(http|https|ftp|ftps)\\:\/\/[a-zA-Z0-9\\-\\.]+\\.[a-zA-Z]{2,3}(\/\\S*)?/" ;
                   $text = $post['description'];
                   // Check if there is a url in the text
                   if(preg_match($reg_exUrl, $text, $url))
                   {
                      // make the urls hyper links
                      echo preg_replace($reg_exUrl, '<a href="'.$url[0].'" rel="nofollow">'.$url[0].'</a>', $text);
                   }
                   else
                   {
                      echo $text;
                   }
                 }
             ?>
          </span>
          
	  </div>
	  <?php endforeach?> 
	  <div class="pagination">
	    <?php if(isset($this->previous)):?>
          <a href="<?php echo $this->url('application/facebook', array('action'=>'pagingVideo', 'id'=> $this->id, 'direction'=>$this->previous, 'tip'=>'prev'));?>"> &lt;&lt; Prethodna </a>
        <?php endif?>
        <?php if(isset($this->next)):?>
          <a href="<?php echo $this->url('application/facebook', array('action'=>'pagingVideo', 'id'=> $this->id, 'direction'=>$this->next, 'tip'=>'next'));?>" style="margin-left: 10px"> Sledeća &gt;&gt; </a>
        <?php endif?>
	  </div>
    </div>
    <div class="col-md-3"><!-- treca kolona login -->       
        <div class="baner">
          <img class="img-responsive" src="<?php echo $this->basePath('img/events.jpg') ?>"/>
       </div>
	   <div class="facebook-groups">
	     <h3>U gradu...</h3>	  
	     <ul class="list-group">
	     <?php foreach($this->face as $grupa) :?>
	       <?php if($grupa->id_tipa==1):?>
	       <li><a href="<?php echo $this->url('application/facebook',array('action'=>'index','id'=>$grupa->id_grupe));?>"><?php echo $grupa->naziv_grupe ?></a></li> 
	       <?php else :?>
	       <li><a href="<?php echo $this->url('application/facebook',array('action'=>'video','id'=>$grupa->id_grupe));?>"><?php echo $grupa->naziv_grupe ?></a></li>
	      <?php endif;?>  
	     <?php endforeach;?>
        </ul>
	  </div>
   
    </div>
  
  </div>
</div>

</body>
</html>
