<body>

 <div class="container" >
  <!-- meni -->
<?php 
  $select = $this->select;
  $select->prepare();
  $select->setAttribute('action', $this->url('application/index', array('controller'=>'index', 'action' => 'sort')));
  $select->setAttribute('method', 'post');
  $select->setAttribute('id','moja');
  $select->setAttribute('role','form');
  $select->setAttribute('class','form-inline');
  echo $this->form()->openTag($select);
 ?>

     <nav class="navbar navbar-inverse">
       <div class="container-fluid">
         <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>                        
            </button>
            <div class="nav-logo">
              <img class="img-responsive" src="<?php echo $this->basePath('img/en-logo.png') ?>"/>
            </div>
         </div>
         <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <li><a href="<?php echo $this->url('application/default');?>" >Početna</a></li>
              <?php if ($this->korisnik == null) :?>
              <li><a href="<?php echo $this->url('application/register',array('action'=>'index'));?>">Registracija</a></li>
              <?php endif?>
              <li class="active"><a href="<?php echo $this->url('application/index',array('action'=>'gallery'));?>" class="current">Galerija</a></li>
              <li><a href="<?php echo $this->url('application/index',array('action'=>'contact'));?>">Kontakt</a></li>
              <li ><a><?php echo $this->formElement($select->get('kategorije')->setAttributes(array('class'=>'select_menu','onChange'=>'document.forms["moja"].submit()'))->setOptions(array('empty_option'=>'Kategorije','value_options'=>$this->kat)));?></a></li>
              <?php if ($this->korisnik != null) :?>
              <li ><a href="<?php echo $this->url('application/index', array('action'=>'logout'));?>">Logout</a></li>
              <li ><a href="<?php echo $this->url('application/korisnik', array('action'=>'index'));?>"><?php echo $this->korisnik?></a></li>
              <?php endif?>        
           </ul>
        </div>
      </div>
     </nav>

 <?php echo $this->form()->closeTag()?>
 <!-- kraj menija -->
    
  <div class="row">
    <div class="col-md-2"></div><!-- prva kolona prazna -->
    <div class="col-md-7"><!-- druga kolona forma-->
      <div class="contact">
        <h4>Post</h4>
        <?php if ($this->error): ?>
        <p class="error">Nastala je greška tokom popunjavanja forme</p>
        <?php endif ?>
        <?php if ($this->mssg): ?>
        <p class="error">Post je uspešno dodat</p>
        <?php endif ?>
	
		<?php
           $form = $this->form;
           $form->prepare();
           $form->setAttribute('action', $this->url(NULL,array('controller'=>'korisnik', 'action' => 'createpost')));
           $form->setAttribute('method', 'post');
           $form->setAttribute('role','form');
           $form->setAttribute('class','form-horizontal');
           echo $this->form()->openTag($form);
         ?>
         <div class="contact-form">
           <div class="form-group">
             <label class="control-label col-sm-2"><?php echo $this->formLabel($form->get('naslov')); ?></label>
             <div class="col-sm-8">
                <?php 
                    echo $this->formElement($form->get('naslov')->setAttributes(array('class'=>'form-control input-sm')));
                    echo $this->formElementErrors($form->get('naslov')->setAttributes(array('class'=>'form-control input-sm')));
                 ?>
             </div>
           </div>
           <div class="form-group">
             <label class="control-label col-sm-2"><?php echo $this->formLabel($form->get('id_kat')); ?></label>
             <div class="col-sm-4">
                <?php 
                    echo $this->formElement($form->get('id_kat')->setAttributes(array('class'=>'form-control input-sm'))->setOptions(array('value_options'=> $this->kat)));
                    echo $this->formElementErrors($form->get('id_kat')->setAttributes(array('class'=>'form-control input-sm')));
                 ?>
             </div>
           </div>
           <div class="form-group">
             <label class="control-label col-sm-2"><?php echo $this->formLabel($form->get('dat_od')); ?></label>
             <div class="col-sm-4">
                <?php 
                    echo $this->formElement($form->get('dat_od')->setAttributes(array('class'=>'form-control input-sm')));
                    echo $this->formElementErrors($form->get('dat_od')->setAttributes(array('class'=>'form-control input-sm')));
                 ?>
             </div>
           </div>
           <div class="form-group">
             <label class="control-label col-sm-2"><?php echo $this->formLabel($form->get('dat_do')); ?></label>
             <div class="col-sm-4">
                <?php 
                    echo $this->formElement($form->get('dat_do')->setAttributes(array('class'=>'form-control input-sm')));
                    echo $this->formElementErrors($form->get('dat_do')->setAttributes(array('class'=>'form-control input-sm')));
                 ?>
             </div>
           </div>
           <div class="form-group">
             <label class="control-label col-sm-2"><?php echo $this->formLabel($form->get('vreme')); ?></label>
             <div class="col-sm-4">
                <?php 
                    echo $this->formElement($form->get('vreme')->setAttributes(array('class'=>'form-control input-sm')));
                    echo $this->formElementErrors($form->get('vreme')->setAttributes(array('class'=>'form-control input-sm')));
                 ?>
             </div>
           </div>
           <div class="form-group">
             <label class="control-label col-sm-2"><?php echo $this->formLabel($form->get('lokacija')); ?></label>
             <div class="col-sm-8">
                <?php 
                    echo $this->formElement($form->get('lokacija')->setAttributes(array('class'=>'form-control input-sm')));
                    echo $this->formElementErrors($form->get('lokacija')->setAttributes(array('class'=>'form-control input-sm')));
                 ?>
             </div>
           </div>
           <div class="form-group">
             <label class="control-label col-sm-2"><?php echo $this->formLabel($form->get('slika')); ?></label>
             <div class="col-sm-8">
                <?php 
                    echo $this->formElement($form->get('slika')->setAttributes(array('class'=>'form-control input-sm')));
                    echo $this->formElementErrors($form->get('slika')->setAttributes(array('class'=>'form-control input-sm')));
                 ?>
             </div>
           </div>
           <div class="form-group">
             <label class="control-label col-sm-2"><?php echo $this->formLabel($form->get('tekst')); ?></label>
             <div class="col-sm-8">
                <?php 
                    echo $this->formElement($form->get('tekst')->setAttributes(array('class'=>'form-control input-sm','rows'=>'5')));
                    echo $this->formElementErrors($form->get('tekst')->setAttributes(array('class'=>'form-control input-sm')));
                 ?>
             </div>
           </div>
           <div class="form-group">
             <div class="col-sm-offset-2 col-sm-10">
                <?php 
                    echo $this->formElement($form->get('submit')->setAttributes(array('class'=>'btn btn-default')));
                    echo $this->formElementErrors($form->get('submit')->setAttributes(array('class'=>'btn btn-default')));
                 ?>
             </div>
           </div>                
           </div>
           <?php echo $this->form()->closeTag()?>  
       </div>
    </div>   
    <div class="col-md-3"><!-- treca kolona login -->       
       <div class="baner">
          <img class="img-responsive" src="<?php echo $this->basePath('img/events.jpg') ?>"/>
       </div>
	   <div class="facebook-groups">
	     <h3>U gradu...</h3>	  
	     <ul class="list-group">
	     <?php foreach($this->face as $grupa) :?>
	       <?php if($grupa->id_tipa==1):?>
	       <li><a href="<?php echo $this->url('application/facebook',array('action'=>'index','id'=>$grupa->id_grupe));?>"><?php echo $grupa->naziv_grupe ?></a></li> 
	       <?php else :?>
	       <li><a href="<?php echo $this->url('application/facebook',array('action'=>'video','id'=>$grupa->id_grupe));?>"><?php echo $grupa->naziv_grupe ?></a></li>
	      <?php endif;?>  
	     <?php endforeach;?>
        </ul>
	  </div>
   
    </div>
  
  </div>
</div>

</body>
</html>
